language: java
sudo: false
install: true
addons:
  sonarqube: true

jdk:
  - oraclejdk8

script:
  - echo "source /etc/mavenrc" >> ~/.mavenrc
  - echo "export MAVEN_OPTS='$MAVEN_OPTS -Dsonar.host.url=https://nemo.sonarqube.org'" >> ~/.mavenrc
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -B -e -V -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
